# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Mistus.CopyPasta
PackageVersion: 1.3.13
PackageLocale: es-US
Publisher: Mistus Project
PackageName: Mistus Copy Pasta
License: MIT
ShortDescription: Fast, private clipboard manager with floating quick-paste island and 2FA authenticator.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
