# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mistus.CopyPasta
PackageVersion: 1.3.13
InstallerType: inno
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/mistu01/copypastapro/releases/download/v1.3.13/Mistus_Copy_Pasta_Setup_v1.3.13.exe
  InstallerSha256: 401E665A7227D3E002F499B2BEF5B453180978BF20DB30F371E9B37EA6475926
ManifestType: installer
ManifestVersion: 1.12.0
